### ISSUE TITLE
[3.0.3] Invalid dist: DEDICATED_SERVER

### ISSUE THREAD

**Issue by No3371** [PssbleTrngle/Brazier#68]
**Describe the bug**
```
-- Head --
Thread: main
Stacktrace:
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.1.2.jar:36.1] {}
-- MOD brazier --
Details:
        Mod File: brazier-3.0.3-forge.jar
        Failure message: Brazier (brazier) has failed to load correctly
                java.lang.RuntimeException: Attempted to load class net/minecraft/client/particle/Particle for invalid dist DEDICATED_SERVER
        Mod Version: 3.0.3
        Mod Issue URL: https://github.com/PssbleTrngle/Brazier/issues
        Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/particle/Particle for invalid dist DEDICATED_SERVER
Stacktrace:
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.1.2.jar:36.1] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261] {}
        at com.possible_triangle.brazier.forge.BrazierForge.<init>(BrazierForge.java:28) ~[brazier:?] {re:classloading,pl:runtimedistcleaner:A}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261] {}
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261] {}
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261] {}
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_261] {}
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_261] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[forge:36.1] {re:classloading}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_261] {}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_261] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_261] {}
```

**To Reproduce**
Launch server with Brazier.

**Version**
Modloader: Forge
Modloader Version: 36.1.2
Mod Version: 3.0.3

**Comment by PssbleTrngle** [comment]
Fixed in version `3.0.4`
