### ISSUE TITLE
Parsing error loading recipe brazier:deploying/living torch

### ISSUE THREAD

**Issue by RayWilliamsII** [PssbleTrngle/Brazier#95]
### What happened?

Forge server reports a parsing error during startup.
The error is thrown by RecipeManager while parsing the create:deploying recipe type for living_torch.
There is a second error thrown by ServerAdvancementManager while attempting to parse the location field for brazier:brazier.

No errors are recorded when the Minecraft client launcher loads the same mods with the same Forge version for single player mode.  This appears to only occur with the Forge Server

The server is still playable, but I don't know if there are any side effects from the error that I haven't run into yet.  There is a warning in the log, prior to the error, that mentions the 'brazier-forge-forge-refmap.json' file not being readable.

Server - Windows 10 Professional
Java - OpenJDK 17.0.6
Forge Version - 47.0.35 - 1.20.1

Forge Server Mod List:
<details><summary>Details</summary>
<p>
almostunified-forge-1.20.1-0.5.0.jar<br/>
architectury-9.0.8-forge.jar<br/>
balm-forge-1.20-7.0.4.jar<br/>
BetterAnimationsCollection-v8.0.0-1.20.1-Forge.jar<br/>
bettervillage-forge-1.20.1-3.1.0.jar<br/>
brazier-forge-6.0.0.jar<br/>
Chimes-v2.0.0-1.20.1.jar<br/>
cloth-config-11.0.99-forge.jar<br/>
curios-forge-5.2.0-beta.3+1.20.1.jar<br/>
findercompass-1.20.1.0.jar<br/>
geckolib-forge-1.20.1-4.2.1.jar<br/>
jei-1.20.1-forge-15.1.0.19.jar<br/>
journeymap-1.20.1-5.9.9-forge.jar<br/>
LeavesBeGone-v8.0.0-1.20.1-Forge.jar<br/>
libraryferret-forge-1.20.1-4.0.0.jar<br/>
lootr-1.20-0.7.30.73.jar<br/>
mcw-bridges-2.1.1-mc1.20.1forge.jar<br/>
mcw-paths-1.0.3forge-mc1.20.1.jar<br/>
modonomicon-1.20.1-1.37.0.jar<br/>
occultism-1.20.1-1.81.0.jar<br/>
Patchouli-1.20.1-80-FORGE.jar<br/>
PuzzlesLib-v8.0.0-1.20.1-Forge.jar<br/>
SmartBrainLib-forge-1.20-1.11.jar<br/>
sophisticatedbackpacks-1.20.1-3.18.55.884.jar<br/>
sophisticatedcore-1.20.1-0.5.78.366.jar<br/>
theurgy-1.20.1-1.3.7.jar<br/>
waystones-forge-1.20-14.0.0.jar
</p>
</details> 

_Note: I selected 1.2 for the MC version assuming it meant 1.20_

### Mod Version

6.0.0

### Minecraft Version

1.2

### Minecraft Loader

Forge

### Fabric/Forge Version

47.0.35

### Relevant log output

```shell
[11:06:55] [main/WARN] [mixin/]: Reference map 'brazier-forge-forge-refmap.json' for brazier-forge.mixins.json could not be read. If this is a development environment you can ignore this message
...
[11:07:07] [main/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe brazier:deploying/living_torch
com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'create:deploying'
	at net.minecraft.world.item.crafting.RecipeManager.m_220253_(RecipeManager.java:170) ~[server-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:mixin,re:classloading,pl:mixin:APP:almostunified-common.mixins.json:runtime.RecipeManagerMixin,pl:mixin:A}
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
	at net.minecraft.world.item.crafting.RecipeManager.fromJson(RecipeManager.java:169) ~[server-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:mixin,re:classloading,pl:mixin:APP:almostunified-common.mixins.json:runtime.RecipeManagerMixin,pl:mixin:A}
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:67) ~[server-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:mixin,re:classloading,pl:mixin:APP:almostunified-common.mixins.json:runtime.RecipeManagerMixin,pl:mixin:A}
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34) ~[server-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:mixin,re:classloading,pl:mixin:APP:almostunified-common.mixins.json:runtime.RecipeManagerMixin,pl:mixin:A}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:classloading,re:mixin}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:classloading}
	at net.minecraft.Util.m_214652_(Util.java:783) ~[server-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:classloading}
	at net.minecraft.Util.m_214679_(Util.java:772) ~[server-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:166) ~[server-1.20.1-20230612.114412-srg.jar%23155!/:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.0.35.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.0.35.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.0.35.jar%2369!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
[11:07:07] [main/INFO] [minecraft/RecipeManager]: Loaded 13 recipes
[11:07:07] [main/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement brazier:brazier: Failed to parse 'location' field
```

**Comment by PssbleTrngle** [comment]
Hi, this is not a problem, it just means that the recipe (which is only valid when create is present) could not be parsed.
It's only there for optional create compat.

Not quite sure about the refmap thing, I'll look if that's a problem

**Comment by PssbleTrngle** [comment]
Ok no the refmap warning does also not matter.
The only thing that's an issue is the advancement parse error on the last line, I'll look into that

**Comment by PssbleTrngle** [comment]
Fixed the advancement in & will update with a new version soon.
Just a heads up, the error logged by the RecipeManager is a very common one and should really be a warning. It is thrown every time a recipe with an unknown type is found, which happens all the time with mods that provide recipes for custom recipe types of other mods. (in this case a recipe for the deployed from create)
