### ISSUE TITLE
REI compat not compatible on server side

### ISSUE THREAD

**Issue by Zifiv** [PssbleTrngle/Brazier#99]
### What happened?

Hello,

It appear that if Brazier is installed on server side with REI (version 9.1.643), since the version 5.0.1 (and the REI/JEI compat), there is an error that is thrown at server startup (see stacktrace below).

I think it is caused by the entry point you are using, `rei_common`, you should use `rei_client` because you implements the class `REIClientPlugin`.

### Mod Version

5.1.0

### Minecraft Version

1.19

### Minecraft Loader

Fabric

### Fabric/Forge Version

Minecraft 1.19.2 with Fabric Loader 0.14.22

### Relevant log output

```shell
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughitems'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.22.jar:?]
	at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.22.jar:?]
Caused by: java.lang.RuntimeException: Failed to initialize REI entry point: me.shedaniel.rei.RoughlyEnoughItemsCore
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:88) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198) ~[?:?]
	at com.sun.proxy.jdk.proxy3.$Proxy45.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
	... 7 more
Caused by: java.lang.RuntimeException: Rerached side issue when loading REI plugin by Brazier. Please use "rei_server", "rei_client" or "rei_common" instead.
	at me.shedaniel.rei.RoughlyEnoughItemsState.error(RoughlyEnoughItemsState.java:52) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.fabric.PluginDetectorImpl.loadPlugin(PluginDetectorImpl.java:108) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.fabric.PluginDetectorImpl.detectCommonPlugins(PluginDetectorImpl.java:139) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore.onInitialize(RoughlyEnoughItemsCore.java:172) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:84) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-9.1.643.jar:?]
	at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198) ~[?:?]
	at com.sun.proxy.jdk.proxy3.$Proxy45.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
	... 7 more
```

**Comment by PssbleTrngle** [comment]
Changed to rei_client in the newest release
